name: deployment
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material markdown-captions mkdocs-markdownextradata-plugin
      - run: mkdir -p docs/architecture/contracts
      - run: git clone --branch master https://github.com/nevermined-io/contracts.git _contracts
      - run: cp -rf _contracts/docs/* docs/architecture/contracts/
      - run: mkdocs gh-deploy --force
